repos:
- path: cann/ge
  display_name: GE
  enabled: true
  notify: true
  goals:
  - metric: star
    label: Star 数
    targets:
    - label: 2026年上半年达到500
      target: 500
    - label: 2026年底达到1000
      target: 1000
  - metric: d1
    label: 外部D1 开发者数量
    targets:
    - date: '2026-06-30'
      target: 60
    - date: '2026-09-30'
      target: 130
    - date: '2026-12-30'
      target: 200
  - metric: d2
    label: 外部D2 开发者数量
    targets:
    - date: '2026-06-30'
      target: 6
    - date: '2026-09-30'
      target: 13
    - date: '2026-12-30'
      target: 20
- path: cann/hixl
  display_name: hixl
  enabled: true
  notify: true
  goals:
  - metric: star
    label: Star 数
    targets:
    - label: 2026年上半年达到700
      target: 700
  - metric: d1
    label: 外部D1 开发者数量
    targets:
    - date: '2026-06-30'
      target: 60
    - date: '2026-09-30'
      target: 150
    - date: '2026-12-30'
      target: 200
  - metric: d2
    label: 外部D2 开发者数量
    targets:
    - date: '2026-06-30'
      target: 10
    - date: '2026-09-30'
      target: 20
    - date: '2026-12-30'
      target: 30
- path: cann/graph-autofusion
  display_name: auto-fusion
  enabled: true
  notify: true
  goals:
  - metric: star
    label: Star 数
    targets:
    - label: 2026年上半年达到500
      target: 500
  - metric: d1
    label: 外部D1 开发者数量
    targets:
    - date: '2026-06-30'
      target: 80
    - date: '2026-09-30'
      target: 150
    - date: '2026-12-30'
      target: 200
  - metric: d2
    label: 外部D2 开发者数量
    targets:
    - date: '2026-06-30'
      target: 10
    - date: '2026-09-30'
      target: 20
    - date: '2026-12-30'
      target: 30
- path: cann/torchtitan-npu
  display_name: torchtitan-npu
  enabled: true
  notify: true
  goals:
  - metric: star
    label: Star 数
    targets:
    - label: 2026年上半年达到300
      target: 300
  - metric: d1
    label: 外部D1 开发者数量
    targets:
    - date: '2026-06-30'
      target: 50
    - date: '2026-09-30'
      target: 120
    - date: '2026-12-30'
      target: 200
  - metric: d2
    label: 外部D2 开发者数量
    targets:
    - date: '2026-06-30'
      target: 5
    - date: '2026-09-30'
      target: 16
    - date: '2026-12-30'
      target: 30
- path: Ascend/torchair
  display_name: TorchAir
  enabled: true
  notify: false
  goals:
  - metric: star
    label: Star 数
    targets:
    - label: 2026年上半年达到700
      target: 700
  - metric: d1
    label: 外部D1 开发者数量
    targets:
    - date: '2026-06-30'
      target: 100
    - date: '2026-09-30'
      target: 150
    - date: '2026-12-30'
      target: 200
  - metric: d2
    label: 外部D2 开发者数量
    targets:
    - date: '2026-06-30'
      target: 10
    - date: '2026-09-30'
      target: 20
    - date: '2026-12-30'
      target: 30